"use client";

import { useState } from "react";
import { Line } from "react-chartjs-2";
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from "chart.js";

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);

export default function SuperuserDashboard() {
  const [activity, setActivity] = useState([
    { id: 1, action: "User Alice created order #123", time: "2h ago" },
    { id: 2, action: "Inventory updated by Bob", time: "4h ago" },
    { id: 3, action: "Report generated by Charlie", time: "6h ago" },
  ]);

  const statsData = {
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    datasets: [
      {
        label: "Orders",
        data: [20, 25, 18, 30, 22, 28, 26],
        borderColor: "#F97316",
        backgroundColor: "rgba(249,115,22,0.1)",
        tension: 0.4,
      },
    ],
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-orange-50 to-white font-sans">
      {/* Header */}
      <header className="p-8 flex justify-between items-center">
        <h1 className="text-3xl font-bold text-orange-700">🔥 Superuser Dashboard</h1>
        <div className="flex items-center space-x-4">
          <span className="text-gray-500">Nov 22, 2025</span>
          <div className="w-10 h-10 rounded-full bg-orange-700 text-white flex items-center justify-center font-bold">S</div>
        </div>
      </header>

      {/* Stats Cards */}
      <div className="px-8 grid grid-cols-1 sm:grid-cols-3 gap-6 mb-8">
        <div className="bg-white shadow-lg rounded-xl p-6 hover:scale-105 transform transition">
          <h2 className="text-sm text-gray-400">Total Orders</h2>
          <p className="text-2xl font-bold text-orange-700">256</p>
        </div>
        <div className="bg-white shadow-lg rounded-xl p-6 hover:scale-105 transform transition">
          <h2 className="text-sm text-gray-400">Active Users</h2>
          <p className="text-2xl font-bold text-orange-700">48</p>
        </div>
        <div className="bg-white shadow-lg rounded-xl p-6 hover:scale-105 transform transition">
          <h2 className="text-sm text-gray-400">Reports Generated</h2>
          <p className="text-2xl font-bold text-orange-700">32</p>
        </div>
      </div>

      {/* Charts */}
      <div className="px-8 bg-white shadow-lg rounded-xl p-6 mb-8">
        <h2 className="text-xl font-semibold text-gray-700 mb-4">Weekly Orders Overview</h2>
        <Line data={statsData} />
      </div>

      {/* Recent Activity */}
      <div className="px-8 bg-white shadow-lg rounded-xl p-6 mb-8">
        <h2 className="text-xl font-semibold text-gray-700 mb-4">Recent Activity</h2>
        <ul className="space-y-3">
          {activity.map((item) => (
            <li key={item.id} className="flex justify-between bg-orange-50 rounded-lg p-4 shadow hover:bg-orange-100 transition">
              <span>{item.action}</span>
              <span className="text-gray-400 text-sm">{item.time}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Quick Links */}
      <div className="px-8 grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
        <a href="/admin/inventory" className="bg-orange-100 hover:bg-orange-200 text-orange-800 p-4 rounded-xl text-center shadow transition">Inventory</a>
        <a href="/order" className="bg-orange-100 hover:bg-orange-200 text-orange-800 p-4 rounded-xl text-center shadow transition">Orders</a>
        <a href="/reports" className="bg-orange-100 hover:bg-orange-200 text-orange-800 p-4 rounded-xl text-center shadow transition">Reports</a>
        <a href="/users" className="bg-orange-100 hover:bg-orange-200 text-orange-800 p-4 rounded-xl text-center shadow transition">Users</a>
      </div>

      {/* Footer */}
      <footer className="px-8 py-6 text-gray-400 text-sm text-center">
        © 2025 Superuser Dashboard. All rights reserved.
      </footer>
    </div>
  );
}
